development:
  adapter: postgresql
  encoding: unicode
  database: hnjs
  pool: 5
  username: sunwooyang

test:
  adapter: postgresql
  encoding: unicode
  database: hnjs
  pool: 5
  username: yangsunwoo

